/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface ErrorResponse {
    error: string;
    /** @nullable */
    attemptsLeft?: number | null;
}
export interface SuccessResponse {
    success: boolean;
    message?: string;
}
export interface LoginInput {
    username: string;
    password: string;
}
export type UserRole = typeof UserRole[keyof typeof UserRole];
export declare const UserRole: {
    readonly admin: "admin";
    readonly member: "member";
};
export interface User {
    id: number;
    username: string;
    role: UserRole;
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    /** @nullable */
    expiresAt?: string | null;
    createdAt: string;
}
export interface AuthResponse {
    user: User;
    token: string;
}
export type UserInputRole = typeof UserInputRole[keyof typeof UserInputRole];
export declare const UserInputRole: {
    readonly admin: "admin";
    readonly member: "member";
};
export interface UserInput {
    username: string;
    password: string;
    role: UserInputRole;
    balance?: number;
    /** @nullable */
    expiresAt?: string | null;
}
export type UserUpdateRole = typeof UserUpdateRole[keyof typeof UserUpdateRole];
export declare const UserUpdateRole: {
    readonly admin: "admin";
    readonly member: "member";
};
export interface UserUpdate {
    username?: string;
    password?: string;
    role?: UserUpdateRole;
    balance?: number;
    isBlocked?: boolean;
    /** @nullable */
    expiresAt?: string | null;
}
export type BalanceAdjustMode = typeof BalanceAdjustMode[keyof typeof BalanceAdjustMode];
export declare const BalanceAdjustMode: {
    readonly add: "add";
    readonly set: "set";
};
export interface BalanceAdjust {
    amount: number;
    mode: BalanceAdjustMode;
}
export interface TransferInput {
    toUsername: string;
    amount: number;
}
export interface TransferResult {
    success: boolean;
    fromBalance: number;
    toUsername: string;
    amount: number;
}
export interface RenewInput {
    days: number;
}
export type ChestType = typeof ChestType[keyof typeof ChestType];
export declare const ChestType: {
    readonly basic: "basic";
    readonly rare: "rare";
    readonly mythic: "mythic";
};
export interface Chest {
    id: number;
    name: string;
    type: ChestType;
    /** @nullable */
    imageUrl?: string | null;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
}
export type ChestInputType = typeof ChestInputType[keyof typeof ChestInputType];
export declare const ChestInputType: {
    readonly basic: "basic";
    readonly rare: "rare";
    readonly mythic: "mythic";
};
export interface ChestInput {
    name: string;
    type: ChestInputType;
    imageUrl?: string;
    costPerPull: number;
    isActive?: boolean;
}
export type ChestUpdateType = typeof ChestUpdateType[keyof typeof ChestUpdateType];
export declare const ChestUpdateType: {
    readonly basic: "basic";
    readonly rare: "rare";
    readonly mythic: "mythic";
};
export interface ChestUpdate {
    name?: string;
    type?: ChestUpdateType;
    imageUrl?: string;
    costPerPull?: number;
    isActive?: boolean;
}
export type GachaItemRarity = typeof GachaItemRarity[keyof typeof GachaItemRarity];
export declare const GachaItemRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
export interface GachaItem {
    id: number;
    chestId: number;
    name: string;
    /** @nullable */
    imageUrl?: string | null;
    chance: number;
    rarity: GachaItemRarity;
}
export type GachaItemInputRarity = typeof GachaItemInputRarity[keyof typeof GachaItemInputRarity];
export declare const GachaItemInputRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
export interface GachaItemInput {
    chestId: number;
    name: string;
    imageUrl?: string;
    chance: number;
    rarity: GachaItemInputRarity;
}
export type GachaItemUpdateRarity = typeof GachaItemUpdateRarity[keyof typeof GachaItemUpdateRarity];
export declare const GachaItemUpdateRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
export interface GachaItemUpdate {
    name?: string;
    imageUrl?: string;
    chance?: number;
    rarity?: GachaItemUpdateRarity;
}
export interface GachaPullInput {
    chestId: number;
}
export interface GachaPullResult {
    item: GachaItem;
    chest: Chest;
    remainingBalance: number;
}
export interface GachaHistory {
    id: number;
    itemName: string;
    /** @nullable */
    itemImageUrl?: string | null;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
}
export type GachaStatsTopItemsItem = {
    itemName: string;
    pullCount: number;
};
export interface GachaStats {
    totalPulls: number;
    totalUsers: number;
    activeUsers: number;
    totalBalanceCirculating: number;
    topItems: GachaStatsTopItemsItem[];
}
export type SiteSettingsBgType = typeof SiteSettingsBgType[keyof typeof SiteSettingsBgType];
export declare const SiteSettingsBgType: {
    readonly particles: "particles";
    readonly gradient: "gradient";
    readonly image: "image";
    readonly color: "color";
};
export type SiteSettingsThemeMode = typeof SiteSettingsThemeMode[keyof typeof SiteSettingsThemeMode];
export declare const SiteSettingsThemeMode: {
    readonly dark: "dark";
    readonly light: "light";
};
export interface SiteSettings {
    siteName: string;
    renewalCostPerDay: number;
    maintenanceMode: boolean;
    primaryColor: string;
    bgType: SiteSettingsBgType;
    bgValue: string;
    themeMode: SiteSettingsThemeMode;
    customLabels: string;
    musicUrl: string;
}
export type SiteSettingsUpdateBgType = typeof SiteSettingsUpdateBgType[keyof typeof SiteSettingsUpdateBgType];
export declare const SiteSettingsUpdateBgType: {
    readonly particles: "particles";
    readonly gradient: "gradient";
    readonly image: "image";
    readonly color: "color";
};
export type SiteSettingsUpdateThemeMode = typeof SiteSettingsUpdateThemeMode[keyof typeof SiteSettingsUpdateThemeMode];
export declare const SiteSettingsUpdateThemeMode: {
    readonly dark: "dark";
    readonly light: "light";
};
export interface SiteSettingsUpdate {
    siteName?: string;
    renewalCostPerDay?: number;
    maintenanceMode?: boolean;
    primaryColor?: string;
    bgType?: SiteSettingsUpdateBgType;
    bgValue?: string;
    themeMode?: SiteSettingsUpdateThemeMode;
    customLabels?: string;
    musicUrl?: string;
}
export type ListItemsParams = {
    chest_id?: number;
};
//# sourceMappingURL=api.schemas.d.ts.map