/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Login with username and password
 */
export declare const LoginBody: zod.ZodObject<{
    username: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    password: string;
}, {
    username: string;
    password: string;
}>;
export declare const LoginResponse: zod.ZodObject<{
    user: zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        role: zod.ZodEnum<["admin", "member"]>;
        balance: zod.ZodNumber;
        isBlocked: zod.ZodBoolean;
        failedAttempts: zod.ZodNumber;
        expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        id: number;
        role: "admin" | "member";
        balance: number;
        isBlocked: boolean;
        failedAttempts: number;
        createdAt: string;
        expiresAt?: string | null | undefined;
    }, {
        username: string;
        id: number;
        role: "admin" | "member";
        balance: number;
        isBlocked: boolean;
        failedAttempts: number;
        createdAt: string;
        expiresAt?: string | null | undefined;
    }>;
    token: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    user: {
        username: string;
        id: number;
        role: "admin" | "member";
        balance: number;
        isBlocked: boolean;
        failedAttempts: number;
        createdAt: string;
        expiresAt?: string | null | undefined;
    };
    token: string;
}, {
    user: {
        username: string;
        id: number;
        role: "admin" | "member";
        balance: number;
        isBlocked: boolean;
        failedAttempts: number;
        createdAt: string;
        expiresAt?: string | null | undefined;
    };
    token: string;
}>;
/**
 * @summary Logout current user
 */
export declare const LogoutResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    message?: string | undefined;
}, {
    success: boolean;
    message?: string | undefined;
}>;
/**
 * @summary Get current logged-in user
 */
export declare const GetMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary List all users (admin only)
 */
export declare const ListUsersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
export declare const ListUsersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new user (admin only)
 */
export declare const CreateUserBody: zod.ZodObject<{
    username: zod.ZodString;
    password: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodOptional<zod.ZodNumber>;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    username: string;
    password: string;
    role: "admin" | "member";
    balance?: number | undefined;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    password: string;
    role: "admin" | "member";
    balance?: number | undefined;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary Get user by ID
 */
export declare const GetUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetUserResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary Update user (admin only)
 */
export declare const UpdateUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateUserBody: zod.ZodObject<{
    username: zod.ZodOptional<zod.ZodString>;
    password: zod.ZodOptional<zod.ZodString>;
    role: zod.ZodOptional<zod.ZodEnum<["admin", "member"]>>;
    balance: zod.ZodOptional<zod.ZodNumber>;
    isBlocked: zod.ZodOptional<zod.ZodBoolean>;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    username?: string | undefined;
    password?: string | undefined;
    role?: "admin" | "member" | undefined;
    balance?: number | undefined;
    isBlocked?: boolean | undefined;
    expiresAt?: string | null | undefined;
}, {
    username?: string | undefined;
    password?: string | undefined;
    role?: "admin" | "member" | undefined;
    balance?: number | undefined;
    isBlocked?: boolean | undefined;
    expiresAt?: string | null | undefined;
}>;
export declare const UpdateUserResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary Delete user (admin only)
 */
export declare const DeleteUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteUserResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    message?: string | undefined;
}, {
    success: boolean;
    message?: string | undefined;
}>;
/**
 * @summary Add or set balance for user (admin only)
 */
export declare const AdjustBalanceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const AdjustBalanceBody: zod.ZodObject<{
    amount: zod.ZodNumber;
    mode: zod.ZodEnum<["add", "set"]>;
}, "strip", zod.ZodTypeAny, {
    amount: number;
    mode: "set" | "add";
}, {
    amount: number;
    mode: "set" | "add";
}>;
export declare const AdjustBalanceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary Transfer balance to another user by username
 */
export declare const TransferBalanceBody: zod.ZodObject<{
    toUsername: zod.ZodString;
    amount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    amount: number;
    toUsername: string;
}, {
    amount: number;
    toUsername: string;
}>;
export declare const TransferBalanceResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    fromBalance: zod.ZodNumber;
    toUsername: zod.ZodString;
    amount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    amount: number;
    toUsername: string;
    fromBalance: number;
}, {
    success: boolean;
    amount: number;
    toUsername: string;
    fromBalance: number;
}>;
/**
 * @summary Renew account expiry using balance (member only)
 */
export declare const RenewAccountBody: zod.ZodObject<{
    days: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    days: number;
}, {
    days: number;
}>;
export declare const RenewAccountResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    role: zod.ZodEnum<["admin", "member"]>;
    balance: zod.ZodNumber;
    isBlocked: zod.ZodBoolean;
    failedAttempts: zod.ZodNumber;
    expiresAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}, {
    username: string;
    id: number;
    role: "admin" | "member";
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    createdAt: string;
    expiresAt?: string | null | undefined;
}>;
/**
 * @summary List all gacha chests
 */
export declare const ListChestsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    type: zod.ZodEnum<["basic", "rare", "mythic"]>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    costPerPull: zod.ZodNumber;
    isActive: zod.ZodBoolean;
    itemCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}>;
export declare const ListChestsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    type: zod.ZodEnum<["basic", "rare", "mythic"]>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    costPerPull: zod.ZodNumber;
    isActive: zod.ZodBoolean;
    itemCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a chest (admin only)
 */
export declare const CreateChestBody: zod.ZodObject<{
    name: zod.ZodString;
    type: zod.ZodEnum<["basic", "rare", "mythic"]>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    costPerPull: zod.ZodNumber;
    isActive: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    type: "basic" | "rare" | "mythic";
    name: string;
    costPerPull: number;
    imageUrl?: string | undefined;
    isActive?: boolean | undefined;
}, {
    type: "basic" | "rare" | "mythic";
    name: string;
    costPerPull: number;
    imageUrl?: string | undefined;
    isActive?: boolean | undefined;
}>;
/**
 * @summary Update chest (admin only)
 */
export declare const UpdateChestParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateChestBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    type: zod.ZodOptional<zod.ZodEnum<["basic", "rare", "mythic"]>>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    costPerPull: zod.ZodOptional<zod.ZodNumber>;
    isActive: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    type?: "basic" | "rare" | "mythic" | undefined;
    name?: string | undefined;
    imageUrl?: string | undefined;
    costPerPull?: number | undefined;
    isActive?: boolean | undefined;
}, {
    type?: "basic" | "rare" | "mythic" | undefined;
    name?: string | undefined;
    imageUrl?: string | undefined;
    costPerPull?: number | undefined;
    isActive?: boolean | undefined;
}>;
export declare const UpdateChestResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    type: zod.ZodEnum<["basic", "rare", "mythic"]>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    costPerPull: zod.ZodNumber;
    isActive: zod.ZodBoolean;
    itemCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}, {
    type: "basic" | "rare" | "mythic";
    id: number;
    name: string;
    costPerPull: number;
    isActive: boolean;
    itemCount: number;
    imageUrl?: string | null | undefined;
}>;
/**
 * @summary Delete chest (admin only)
 */
export declare const DeleteChestParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteChestResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    message?: string | undefined;
}, {
    success: boolean;
    message?: string | undefined;
}>;
/**
 * @summary List all gacha items (optionally filter by chest_id)
 */
export declare const ListItemsQueryParams: zod.ZodObject<{
    chest_id: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    chest_id?: number | undefined;
}, {
    chest_id?: number | undefined;
}>;
export declare const ListItemsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    chestId: zod.ZodNumber;
    name: zod.ZodString;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    chance: zod.ZodNumber;
    rarity: zod.ZodEnum<["common", "rare", "legendary"]>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}>;
export declare const ListItemsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    chestId: zod.ZodNumber;
    name: zod.ZodString;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    chance: zod.ZodNumber;
    rarity: zod.ZodEnum<["common", "rare", "legendary"]>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a gacha item (admin only)
 */
export declare const CreateItemBody: zod.ZodObject<{
    chestId: zod.ZodNumber;
    name: zod.ZodString;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    chance: zod.ZodNumber;
    rarity: zod.ZodEnum<["common", "rare", "legendary"]>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | undefined;
}, {
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | undefined;
}>;
/**
 * @summary Update gacha item (admin only)
 */
export declare const UpdateItemParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateItemBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    chance: zod.ZodOptional<zod.ZodNumber>;
    rarity: zod.ZodOptional<zod.ZodEnum<["common", "rare", "legendary"]>>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    imageUrl?: string | undefined;
    chance?: number | undefined;
    rarity?: "rare" | "common" | "legendary" | undefined;
}, {
    name?: string | undefined;
    imageUrl?: string | undefined;
    chance?: number | undefined;
    rarity?: "rare" | "common" | "legendary" | undefined;
}>;
export declare const UpdateItemResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    chestId: zod.ZodNumber;
    name: zod.ZodString;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    chance: zod.ZodNumber;
    rarity: zod.ZodEnum<["common", "rare", "legendary"]>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    chestId: number;
    chance: number;
    rarity: "rare" | "common" | "legendary";
    imageUrl?: string | null | undefined;
}>;
/**
 * @summary Delete gacha item (admin only)
 */
export declare const DeleteItemParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteItemResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    message?: string | undefined;
}, {
    success: boolean;
    message?: string | undefined;
}>;
/**
 * @summary Pull gacha from a chest
 */
export declare const PullGachaBody: zod.ZodObject<{
    chestId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    chestId: number;
}, {
    chestId: number;
}>;
export declare const PullGachaResponse: zod.ZodObject<{
    item: zod.ZodObject<{
        id: zod.ZodNumber;
        chestId: zod.ZodNumber;
        name: zod.ZodString;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        chance: zod.ZodNumber;
        rarity: zod.ZodEnum<["common", "rare", "legendary"]>;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        chestId: number;
        chance: number;
        rarity: "rare" | "common" | "legendary";
        imageUrl?: string | null | undefined;
    }, {
        id: number;
        name: string;
        chestId: number;
        chance: number;
        rarity: "rare" | "common" | "legendary";
        imageUrl?: string | null | undefined;
    }>;
    chest: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        type: zod.ZodEnum<["basic", "rare", "mythic"]>;
        imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        costPerPull: zod.ZodNumber;
        isActive: zod.ZodBoolean;
        itemCount: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        type: "basic" | "rare" | "mythic";
        id: number;
        name: string;
        costPerPull: number;
        isActive: boolean;
        itemCount: number;
        imageUrl?: string | null | undefined;
    }, {
        type: "basic" | "rare" | "mythic";
        id: number;
        name: string;
        costPerPull: number;
        isActive: boolean;
        itemCount: number;
        imageUrl?: string | null | undefined;
    }>;
    remainingBalance: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    item: {
        id: number;
        name: string;
        chestId: number;
        chance: number;
        rarity: "rare" | "common" | "legendary";
        imageUrl?: string | null | undefined;
    };
    chest: {
        type: "basic" | "rare" | "mythic";
        id: number;
        name: string;
        costPerPull: number;
        isActive: boolean;
        itemCount: number;
        imageUrl?: string | null | undefined;
    };
    remainingBalance: number;
}, {
    item: {
        id: number;
        name: string;
        chestId: number;
        chance: number;
        rarity: "rare" | "common" | "legendary";
        imageUrl?: string | null | undefined;
    };
    chest: {
        type: "basic" | "rare" | "mythic";
        id: number;
        name: string;
        costPerPull: number;
        isActive: boolean;
        itemCount: number;
        imageUrl?: string | null | undefined;
    };
    remainingBalance: number;
}>;
/**
 * @summary Get gacha pull history for current user
 */
export declare const ListGachaHistoryResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    itemName: zod.ZodString;
    itemImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    itemRarity: zod.ZodString;
    chestName: zod.ZodString;
    chestType: zod.ZodString;
    pulledAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    itemName: string;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
    itemImageUrl?: string | null | undefined;
}, {
    id: number;
    itemName: string;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
    itemImageUrl?: string | null | undefined;
}>;
export declare const ListGachaHistoryResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    itemName: zod.ZodString;
    itemImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    itemRarity: zod.ZodString;
    chestName: zod.ZodString;
    chestType: zod.ZodString;
    pulledAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    itemName: string;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
    itemImageUrl?: string | null | undefined;
}, {
    id: number;
    itemName: string;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
    itemImageUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Get gacha statistics (admin dashboard)
 */
export declare const GetGachaStatsResponse: zod.ZodObject<{
    totalPulls: zod.ZodNumber;
    totalUsers: zod.ZodNumber;
    activeUsers: zod.ZodNumber;
    totalBalanceCirculating: zod.ZodNumber;
    topItems: zod.ZodArray<zod.ZodObject<{
        itemName: zod.ZodString;
        pullCount: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        itemName: string;
        pullCount: number;
    }, {
        itemName: string;
        pullCount: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalPulls: number;
    totalUsers: number;
    activeUsers: number;
    totalBalanceCirculating: number;
    topItems: {
        itemName: string;
        pullCount: number;
    }[];
}, {
    totalPulls: number;
    totalUsers: number;
    activeUsers: number;
    totalBalanceCirculating: number;
    topItems: {
        itemName: string;
        pullCount: number;
    }[];
}>;
/**
 * @summary Get site settings
 */
export declare const GetSettingsResponse: zod.ZodObject<{
    siteName: zod.ZodString;
    renewalCostPerDay: zod.ZodNumber;
    maintenanceMode: zod.ZodBoolean;
    primaryColor: zod.ZodString;
    bgType: zod.ZodEnum<["particles", "gradient", "image", "color"]>;
    bgValue: zod.ZodString;
    themeMode: zod.ZodEnum<["dark", "light"]>;
    customLabels: zod.ZodString;
    musicUrl: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    siteName: string;
    renewalCostPerDay: number;
    maintenanceMode: boolean;
    primaryColor: string;
    bgType: "particles" | "gradient" | "image" | "color";
    bgValue: string;
    themeMode: "dark" | "light";
    customLabels: string;
    musicUrl: string;
}, {
    siteName: string;
    renewalCostPerDay: number;
    maintenanceMode: boolean;
    primaryColor: string;
    bgType: "particles" | "gradient" | "image" | "color";
    bgValue: string;
    themeMode: "dark" | "light";
    customLabels: string;
    musicUrl: string;
}>;
/**
 * @summary Update site settings (admin only)
 */
export declare const UpdateSettingsBody: zod.ZodObject<{
    siteName: zod.ZodOptional<zod.ZodString>;
    renewalCostPerDay: zod.ZodOptional<zod.ZodNumber>;
    maintenanceMode: zod.ZodOptional<zod.ZodBoolean>;
    primaryColor: zod.ZodOptional<zod.ZodString>;
    bgType: zod.ZodOptional<zod.ZodEnum<["particles", "gradient", "image", "color"]>>;
    bgValue: zod.ZodOptional<zod.ZodString>;
    themeMode: zod.ZodOptional<zod.ZodEnum<["dark", "light"]>>;
    customLabels: zod.ZodOptional<zod.ZodString>;
    musicUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    siteName?: string | undefined;
    renewalCostPerDay?: number | undefined;
    maintenanceMode?: boolean | undefined;
    primaryColor?: string | undefined;
    bgType?: "particles" | "gradient" | "image" | "color" | undefined;
    bgValue?: string | undefined;
    themeMode?: "dark" | "light" | undefined;
    customLabels?: string | undefined;
    musicUrl?: string | undefined;
}, {
    siteName?: string | undefined;
    renewalCostPerDay?: number | undefined;
    maintenanceMode?: boolean | undefined;
    primaryColor?: string | undefined;
    bgType?: "particles" | "gradient" | "image" | "color" | undefined;
    bgValue?: string | undefined;
    themeMode?: "dark" | "light" | undefined;
    customLabels?: string | undefined;
    musicUrl?: string | undefined;
}>;
export declare const UpdateSettingsResponse: zod.ZodObject<{
    siteName: zod.ZodString;
    renewalCostPerDay: zod.ZodNumber;
    maintenanceMode: zod.ZodBoolean;
    primaryColor: zod.ZodString;
    bgType: zod.ZodEnum<["particles", "gradient", "image", "color"]>;
    bgValue: zod.ZodString;
    themeMode: zod.ZodEnum<["dark", "light"]>;
    customLabels: zod.ZodString;
    musicUrl: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    siteName: string;
    renewalCostPerDay: number;
    maintenanceMode: boolean;
    primaryColor: string;
    bgType: "particles" | "gradient" | "image" | "color";
    bgValue: string;
    themeMode: "dark" | "light";
    customLabels: string;
    musicUrl: string;
}, {
    siteName: string;
    renewalCostPerDay: number;
    maintenanceMode: boolean;
    primaryColor: string;
    bgType: "particles" | "gradient" | "image" | "color";
    bgValue: string;
    themeMode: "dark" | "light";
    customLabels: string;
    musicUrl: string;
}>;
//# sourceMappingURL=api.d.ts.map