/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  /** @nullable */
  attemptsLeft?: number | null;
}

export interface SuccessResponse {
  success: boolean;
  message?: string;
}

export interface LoginInput {
  username: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  member: 'member',
} as const;

export interface User {
  id: number;
  username: string;
  role: UserRole;
  balance: number;
  isBlocked: boolean;
  failedAttempts: number;
  /** @nullable */
  expiresAt?: string | null;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export type UserInputRole = typeof UserInputRole[keyof typeof UserInputRole];


export const UserInputRole = {
  admin: 'admin',
  member: 'member',
} as const;

export interface UserInput {
  username: string;
  password: string;
  role: UserInputRole;
  balance?: number;
  /** @nullable */
  expiresAt?: string | null;
}

export type UserUpdateRole = typeof UserUpdateRole[keyof typeof UserUpdateRole];


export const UserUpdateRole = {
  admin: 'admin',
  member: 'member',
} as const;

export interface UserUpdate {
  username?: string;
  password?: string;
  role?: UserUpdateRole;
  balance?: number;
  isBlocked?: boolean;
  /** @nullable */
  expiresAt?: string | null;
}

export type BalanceAdjustMode = typeof BalanceAdjustMode[keyof typeof BalanceAdjustMode];


export const BalanceAdjustMode = {
  add: 'add',
  set: 'set',
} as const;

export interface BalanceAdjust {
  amount: number;
  mode: BalanceAdjustMode;
}

export interface TransferInput {
  toUsername: string;
  amount: number;
}

export interface TransferResult {
  success: boolean;
  fromBalance: number;
  toUsername: string;
  amount: number;
}

export interface RenewInput {
  days: number;
}

export type ChestType = typeof ChestType[keyof typeof ChestType];


export const ChestType = {
  basic: 'basic',
  rare: 'rare',
  mythic: 'mythic',
} as const;

export interface Chest {
  id: number;
  name: string;
  type: ChestType;
  /** @nullable */
  imageUrl?: string | null;
  costPerPull: number;
  isActive: boolean;
  itemCount: number;
}

export type ChestInputType = typeof ChestInputType[keyof typeof ChestInputType];


export const ChestInputType = {
  basic: 'basic',
  rare: 'rare',
  mythic: 'mythic',
} as const;

export interface ChestInput {
  name: string;
  type: ChestInputType;
  imageUrl?: string;
  costPerPull: number;
  isActive?: boolean;
}

export type ChestUpdateType = typeof ChestUpdateType[keyof typeof ChestUpdateType];


export const ChestUpdateType = {
  basic: 'basic',
  rare: 'rare',
  mythic: 'mythic',
} as const;

export interface ChestUpdate {
  name?: string;
  type?: ChestUpdateType;
  imageUrl?: string;
  costPerPull?: number;
  isActive?: boolean;
}

export type GachaItemRarity = typeof GachaItemRarity[keyof typeof GachaItemRarity];


export const GachaItemRarity = {
  common: 'common',
  rare: 'rare',
  legendary: 'legendary',
} as const;

export interface GachaItem {
  id: number;
  chestId: number;
  name: string;
  /** @nullable */
  imageUrl?: string | null;
  chance: number;
  rarity: GachaItemRarity;
}

export type GachaItemInputRarity = typeof GachaItemInputRarity[keyof typeof GachaItemInputRarity];


export const GachaItemInputRarity = {
  common: 'common',
  rare: 'rare',
  legendary: 'legendary',
} as const;

export interface GachaItemInput {
  chestId: number;
  name: string;
  imageUrl?: string;
  chance: number;
  rarity: GachaItemInputRarity;
}

export type GachaItemUpdateRarity = typeof GachaItemUpdateRarity[keyof typeof GachaItemUpdateRarity];


export const GachaItemUpdateRarity = {
  common: 'common',
  rare: 'rare',
  legendary: 'legendary',
} as const;

export interface GachaItemUpdate {
  name?: string;
  imageUrl?: string;
  chance?: number;
  rarity?: GachaItemUpdateRarity;
}

export interface GachaPullInput {
  chestId: number;
}

export interface GachaPullResult {
  item: GachaItem;
  chest: Chest;
  remainingBalance: number;
}

export interface GachaHistory {
  id: number;
  itemName: string;
  /** @nullable */
  itemImageUrl?: string | null;
  itemRarity: string;
  chestName: string;
  chestType: string;
  pulledAt: string;
}

export type GachaStatsTopItemsItem = {
  itemName: string;
  pullCount: number;
};

export interface GachaStats {
  totalPulls: number;
  totalUsers: number;
  activeUsers: number;
  totalBalanceCirculating: number;
  topItems: GachaStatsTopItemsItem[];
}

export type SiteSettingsBgType = typeof SiteSettingsBgType[keyof typeof SiteSettingsBgType];


export const SiteSettingsBgType = {
  particles: 'particles',
  gradient: 'gradient',
  image: 'image',
  color: 'color',
} as const;

export type SiteSettingsThemeMode = typeof SiteSettingsThemeMode[keyof typeof SiteSettingsThemeMode];


export const SiteSettingsThemeMode = {
  dark: 'dark',
  light: 'light',
} as const;

export interface SiteSettings {
  siteName: string;
  renewalCostPerDay: number;
  maintenanceMode: boolean;
  primaryColor: string;
  bgType: SiteSettingsBgType;
  bgValue: string;
  themeMode: SiteSettingsThemeMode;
  customLabels: string;
  musicUrl: string;
}

export type SiteSettingsUpdateBgType = typeof SiteSettingsUpdateBgType[keyof typeof SiteSettingsUpdateBgType];


export const SiteSettingsUpdateBgType = {
  particles: 'particles',
  gradient: 'gradient',
  image: 'image',
  color: 'color',
} as const;

export type SiteSettingsUpdateThemeMode = typeof SiteSettingsUpdateThemeMode[keyof typeof SiteSettingsUpdateThemeMode];


export const SiteSettingsUpdateThemeMode = {
  dark: 'dark',
  light: 'light',
} as const;

export interface SiteSettingsUpdate {
  siteName?: string;
  renewalCostPerDay?: number;
  maintenanceMode?: boolean;
  primaryColor?: string;
  bgType?: SiteSettingsUpdateBgType;
  bgValue?: string;
  themeMode?: SiteSettingsUpdateThemeMode;
  customLabels?: string;
  musicUrl?: string;
}

export type ListItemsParams = {
chest_id?: number;
};

