/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  BalanceAdjust,
  Chest,
  ChestInput,
  ChestUpdate,
  ErrorResponse,
  GachaHistory,
  GachaItem,
  GachaItemInput,
  GachaItemUpdate,
  GachaPullInput,
  GachaPullResult,
  GachaStats,
  HealthStatus,
  ListItemsParams,
  LoginInput,
  RenewInput,
  SiteSettings,
  SiteSettingsUpdate,
  SuccessResponse,
  TransferInput,
  TransferResult,
  User,
  UserInput,
  UserUpdate
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getLoginUrl = () => {




  return `/api/auth/login`
}

/**
 * @summary Login with username and password
 */
export const login = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInput,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginInput>
    export type LoginMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Login with username and password
 */
export const useLogin = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options));
    }

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary Logout current user
 */
export const logout = async ( options?: RequestInit): Promise<SuccessResponse> => {

  return customFetch<SuccessResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {


          return  logout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>

    export type LogoutMutationError = ErrorType<unknown>

    /**
 * @summary Logout current user
 */
export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options));
    }

export const getGetMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary Get current logged-in user
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get current logged-in user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListUsersUrl = () => {




  return `/api/users`
}

/**
 * @summary List all users (admin only)
 */
export const listUsers = async ( options?: RequestInit): Promise<User[]> => {

  return customFetch<User[]>(getListUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }


export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ErrorType<unknown>


/**
 * @summary List all users (admin only)
 */

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateUserUrl = () => {




  return `/api/users`
}

/**
 * @summary Create a new user (admin only)
 */
export const createUser = async (userInput: UserInput, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getCreateUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userInput,)
  }
);}




export const getCreateUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<UserInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<UserInput>}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: BodyType<UserInput>}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = BodyType<UserInput>
    export type CreateUserMutationError = ErrorType<unknown>

    /**
 * @summary Create a new user (admin only)
 */
export const useCreateUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<UserInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: BodyType<UserInput>},
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options));
    }

export const getGetUserUrl = (id: number,) => {




  return `/api/users/${id}`
}

/**
 * @summary Get user by ID
 */
export const getUser = async (id: number, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetUserUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserQueryKey = (id: number,) => {
    return [
    `/api/users/${id}`
    ] as const;
    }


export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = ErrorType<unknown>


/**
 * @summary Get user by ID
 */

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateUserUrl = (id: number,) => {




  return `/api/users/${id}`
}

/**
 * @summary Update user (admin only)
 */
export const updateUser = async (id: number,
    userUpdate: UserUpdate, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getUpdateUserUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUpdate,)
  }
);}




export const getUpdateUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserUpdate>}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: BodyType<UserUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = BodyType<UserUpdate>
    export type UpdateUserMutationError = ErrorType<unknown>

    /**
 * @summary Update user (admin only)
 */
export const useUpdateUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: BodyType<UserUpdate>},
        TContext
      > => {
      return useMutation(getUpdateUserMutationOptions(options));
    }

export const getDeleteUserUrl = (id: number,) => {




  return `/api/users/${id}`
}

/**
 * @summary Delete user (admin only)
 */
export const deleteUser = async (id: number, options?: RequestInit): Promise<SuccessResponse> => {

  return customFetch<SuccessResponse>(getDeleteUserUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>

    export type DeleteUserMutationError = ErrorType<unknown>

    /**
 * @summary Delete user (admin only)
 */
export const useDeleteUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options));
    }

export const getAdjustBalanceUrl = (id: number,) => {




  return `/api/users/${id}/balance`
}

/**
 * @summary Add or set balance for user (admin only)
 */
export const adjustBalance = async (id: number,
    balanceAdjust: BalanceAdjust, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getAdjustBalanceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      balanceAdjust,)
  }
);}




export const getAdjustBalanceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustBalance>>, TError,{id: number;data: BodyType<BalanceAdjust>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof adjustBalance>>, TError,{id: number;data: BodyType<BalanceAdjust>}, TContext> => {

const mutationKey = ['adjustBalance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adjustBalance>>, {id: number;data: BodyType<BalanceAdjust>}> = (props) => {
          const {id,data} = props ?? {};

          return  adjustBalance(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdjustBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof adjustBalance>>>
    export type AdjustBalanceMutationBody = BodyType<BalanceAdjust>
    export type AdjustBalanceMutationError = ErrorType<unknown>

    /**
 * @summary Add or set balance for user (admin only)
 */
export const useAdjustBalance = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustBalance>>, TError,{id: number;data: BodyType<BalanceAdjust>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof adjustBalance>>,
        TError,
        {id: number;data: BodyType<BalanceAdjust>},
        TContext
      > => {
      return useMutation(getAdjustBalanceMutationOptions(options));
    }

export const getTransferBalanceUrl = () => {




  return `/api/balance/transfer`
}

/**
 * @summary Transfer balance to another user by username
 */
export const transferBalance = async (transferInput: TransferInput, options?: RequestInit): Promise<TransferResult> => {

  return customFetch<TransferResult>(getTransferBalanceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transferInput,)
  }
);}




export const getTransferBalanceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferBalance>>, TError,{data: BodyType<TransferInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof transferBalance>>, TError,{data: BodyType<TransferInput>}, TContext> => {

const mutationKey = ['transferBalance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transferBalance>>, {data: BodyType<TransferInput>}> = (props) => {
          const {data} = props ?? {};

          return  transferBalance(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TransferBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof transferBalance>>>
    export type TransferBalanceMutationBody = BodyType<TransferInput>
    export type TransferBalanceMutationError = ErrorType<unknown>

    /**
 * @summary Transfer balance to another user by username
 */
export const useTransferBalance = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferBalance>>, TError,{data: BodyType<TransferInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof transferBalance>>,
        TError,
        {data: BodyType<TransferInput>},
        TContext
      > => {
      return useMutation(getTransferBalanceMutationOptions(options));
    }

export const getRenewAccountUrl = () => {




  return `/api/balance/renew`
}

/**
 * @summary Renew account expiry using balance (member only)
 */
export const renewAccount = async (renewInput: RenewInput, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getRenewAccountUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      renewInput,)
  }
);}




export const getRenewAccountMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renewAccount>>, TError,{data: BodyType<RenewInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof renewAccount>>, TError,{data: BodyType<RenewInput>}, TContext> => {

const mutationKey = ['renewAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renewAccount>>, {data: BodyType<RenewInput>}> = (props) => {
          const {data} = props ?? {};

          return  renewAccount(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenewAccountMutationResult = NonNullable<Awaited<ReturnType<typeof renewAccount>>>
    export type RenewAccountMutationBody = BodyType<RenewInput>
    export type RenewAccountMutationError = ErrorType<unknown>

    /**
 * @summary Renew account expiry using balance (member only)
 */
export const useRenewAccount = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renewAccount>>, TError,{data: BodyType<RenewInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof renewAccount>>,
        TError,
        {data: BodyType<RenewInput>},
        TContext
      > => {
      return useMutation(getRenewAccountMutationOptions(options));
    }

export const getListChestsUrl = () => {




  return `/api/chests`
}

/**
 * @summary List all gacha chests
 */
export const listChests = async ( options?: RequestInit): Promise<Chest[]> => {

  return customFetch<Chest[]>(getListChestsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListChestsQueryKey = () => {
    return [
    `/api/chests`
    ] as const;
    }


export const getListChestsQueryOptions = <TData = Awaited<ReturnType<typeof listChests>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChestsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChests>>> = ({ signal }) => listChests({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChests>>, TError, TData> & { queryKey: QueryKey }
}

export type ListChestsQueryResult = NonNullable<Awaited<ReturnType<typeof listChests>>>
export type ListChestsQueryError = ErrorType<unknown>


/**
 * @summary List all gacha chests
 */

export function useListChests<TData = Awaited<ReturnType<typeof listChests>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListChestsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateChestUrl = () => {




  return `/api/chests`
}

/**
 * @summary Create a chest (admin only)
 */
export const createChest = async (chestInput: ChestInput, options?: RequestInit): Promise<Chest> => {

  return customFetch<Chest>(getCreateChestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chestInput,)
  }
);}




export const getCreateChestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChest>>, TError,{data: BodyType<ChestInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createChest>>, TError,{data: BodyType<ChestInput>}, TContext> => {

const mutationKey = ['createChest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChest>>, {data: BodyType<ChestInput>}> = (props) => {
          const {data} = props ?? {};

          return  createChest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateChestMutationResult = NonNullable<Awaited<ReturnType<typeof createChest>>>
    export type CreateChestMutationBody = BodyType<ChestInput>
    export type CreateChestMutationError = ErrorType<unknown>

    /**
 * @summary Create a chest (admin only)
 */
export const useCreateChest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChest>>, TError,{data: BodyType<ChestInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createChest>>,
        TError,
        {data: BodyType<ChestInput>},
        TContext
      > => {
      return useMutation(getCreateChestMutationOptions(options));
    }

export const getUpdateChestUrl = (id: number,) => {




  return `/api/chests/${id}`
}

/**
 * @summary Update chest (admin only)
 */
export const updateChest = async (id: number,
    chestUpdate: ChestUpdate, options?: RequestInit): Promise<Chest> => {

  return customFetch<Chest>(getUpdateChestUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chestUpdate,)
  }
);}




export const getUpdateChestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChest>>, TError,{id: number;data: BodyType<ChestUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateChest>>, TError,{id: number;data: BodyType<ChestUpdate>}, TContext> => {

const mutationKey = ['updateChest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateChest>>, {id: number;data: BodyType<ChestUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateChest(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateChestMutationResult = NonNullable<Awaited<ReturnType<typeof updateChest>>>
    export type UpdateChestMutationBody = BodyType<ChestUpdate>
    export type UpdateChestMutationError = ErrorType<unknown>

    /**
 * @summary Update chest (admin only)
 */
export const useUpdateChest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChest>>, TError,{id: number;data: BodyType<ChestUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateChest>>,
        TError,
        {id: number;data: BodyType<ChestUpdate>},
        TContext
      > => {
      return useMutation(getUpdateChestMutationOptions(options));
    }

export const getDeleteChestUrl = (id: number,) => {




  return `/api/chests/${id}`
}

/**
 * @summary Delete chest (admin only)
 */
export const deleteChest = async (id: number, options?: RequestInit): Promise<SuccessResponse> => {

  return customFetch<SuccessResponse>(getDeleteChestUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteChestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChest>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteChest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChest>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteChest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteChestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChest>>>

    export type DeleteChestMutationError = ErrorType<unknown>

    /**
 * @summary Delete chest (admin only)
 */
export const useDeleteChest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteChest>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteChestMutationOptions(options));
    }

export const getListItemsUrl = (params?: ListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/items?${stringifiedParams}` : `/api/items`
}

/**
 * @summary List all gacha items (optionally filter by chest_id)
 */
export const listItems = async (params?: ListItemsParams, options?: RequestInit): Promise<GachaItem[]> => {

  return customFetch<GachaItem[]>(getListItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListItemsQueryKey = (params?: ListItemsParams,) => {
    return [
    `/api/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listItems>>, TError = ErrorType<unknown>>(params?: ListItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItems>>> = ({ signal }) => listItems(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData> & { queryKey: QueryKey }
}

export type ListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listItems>>>
export type ListItemsQueryError = ErrorType<unknown>


/**
 * @summary List all gacha items (optionally filter by chest_id)
 */

export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = ErrorType<unknown>>(
 params?: ListItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListItemsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateItemUrl = () => {




  return `/api/items`
}

/**
 * @summary Create a gacha item (admin only)
 */
export const createItem = async (gachaItemInput: GachaItemInput, options?: RequestInit): Promise<GachaItem> => {

  return customFetch<GachaItem>(getCreateItemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gachaItemInput,)
  }
);}




export const getCreateItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: BodyType<GachaItemInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: BodyType<GachaItemInput>}, TContext> => {

const mutationKey = ['createItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItem>>, {data: BodyType<GachaItemInput>}> = (props) => {
          const {data} = props ?? {};

          return  createItem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateItemMutationResult = NonNullable<Awaited<ReturnType<typeof createItem>>>
    export type CreateItemMutationBody = BodyType<GachaItemInput>
    export type CreateItemMutationError = ErrorType<unknown>

    /**
 * @summary Create a gacha item (admin only)
 */
export const useCreateItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: BodyType<GachaItemInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createItem>>,
        TError,
        {data: BodyType<GachaItemInput>},
        TContext
      > => {
      return useMutation(getCreateItemMutationOptions(options));
    }

export const getUpdateItemUrl = (id: number,) => {




  return `/api/items/${id}`
}

/**
 * @summary Update gacha item (admin only)
 */
export const updateItem = async (id: number,
    gachaItemUpdate: GachaItemUpdate, options?: RequestInit): Promise<GachaItem> => {

  return customFetch<GachaItem>(getUpdateItemUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gachaItemUpdate,)
  }
);}




export const getUpdateItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: number;data: BodyType<GachaItemUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: number;data: BodyType<GachaItemUpdate>}, TContext> => {

const mutationKey = ['updateItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, {id: number;data: BodyType<GachaItemUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateItem(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = BodyType<GachaItemUpdate>
    export type UpdateItemMutationError = ErrorType<unknown>

    /**
 * @summary Update gacha item (admin only)
 */
export const useUpdateItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: number;data: BodyType<GachaItemUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        {id: number;data: BodyType<GachaItemUpdate>},
        TContext
      > => {
      return useMutation(getUpdateItemMutationOptions(options));
    }

export const getDeleteItemUrl = (id: number,) => {




  return `/api/items/${id}`
}

/**
 * @summary Delete gacha item (admin only)
 */
export const deleteItem = async (id: number, options?: RequestInit): Promise<SuccessResponse> => {

  return customFetch<SuccessResponse>(getDeleteItemUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteItem(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>

    export type DeleteItemMutationError = ErrorType<unknown>

    /**
 * @summary Delete gacha item (admin only)
 */
export const useDeleteItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteItemMutationOptions(options));
    }

export const getPullGachaUrl = () => {




  return `/api/gacha/pull`
}

/**
 * @summary Pull gacha from a chest
 */
export const pullGacha = async (gachaPullInput: GachaPullInput, options?: RequestInit): Promise<GachaPullResult> => {

  return customFetch<GachaPullResult>(getPullGachaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gachaPullInput,)
  }
);}




export const getPullGachaMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pullGacha>>, TError,{data: BodyType<GachaPullInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pullGacha>>, TError,{data: BodyType<GachaPullInput>}, TContext> => {

const mutationKey = ['pullGacha'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pullGacha>>, {data: BodyType<GachaPullInput>}> = (props) => {
          const {data} = props ?? {};

          return  pullGacha(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PullGachaMutationResult = NonNullable<Awaited<ReturnType<typeof pullGacha>>>
    export type PullGachaMutationBody = BodyType<GachaPullInput>
    export type PullGachaMutationError = ErrorType<unknown>

    /**
 * @summary Pull gacha from a chest
 */
export const usePullGacha = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pullGacha>>, TError,{data: BodyType<GachaPullInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof pullGacha>>,
        TError,
        {data: BodyType<GachaPullInput>},
        TContext
      > => {
      return useMutation(getPullGachaMutationOptions(options));
    }

export const getListGachaHistoryUrl = () => {




  return `/api/gacha/history`
}

/**
 * @summary Get gacha pull history for current user
 */
export const listGachaHistory = async ( options?: RequestInit): Promise<GachaHistory[]> => {

  return customFetch<GachaHistory[]>(getListGachaHistoryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGachaHistoryQueryKey = () => {
    return [
    `/api/gacha/history`
    ] as const;
    }


export const getListGachaHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listGachaHistory>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGachaHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGachaHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGachaHistory>>> = ({ signal }) => listGachaHistory({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGachaHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type ListGachaHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listGachaHistory>>>
export type ListGachaHistoryQueryError = ErrorType<unknown>


/**
 * @summary Get gacha pull history for current user
 */

export function useListGachaHistory<TData = Awaited<ReturnType<typeof listGachaHistory>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGachaHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListGachaHistoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetGachaStatsUrl = () => {




  return `/api/gacha/stats`
}

/**
 * @summary Get gacha statistics (admin dashboard)
 */
export const getGachaStats = async ( options?: RequestInit): Promise<GachaStats> => {

  return customFetch<GachaStats>(getGetGachaStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGachaStatsQueryKey = () => {
    return [
    `/api/gacha/stats`
    ] as const;
    }


export const getGetGachaStatsQueryOptions = <TData = Awaited<ReturnType<typeof getGachaStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGachaStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGachaStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGachaStats>>> = ({ signal }) => getGachaStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGachaStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGachaStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getGachaStats>>>
export type GetGachaStatsQueryError = ErrorType<unknown>


/**
 * @summary Get gacha statistics (admin dashboard)
 */

export function useGetGachaStats<TData = Awaited<ReturnType<typeof getGachaStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGachaStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetGachaStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetSettingsUrl = () => {




  return `/api/settings`
}

/**
 * @summary Get site settings
 */
export const getSettings = async ( options?: RequestInit): Promise<SiteSettings> => {

  return customFetch<SiteSettings>(getGetSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSettingsQueryKey = () => {
    return [
    `/api/settings`
    ] as const;
    }


export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = ErrorType<unknown>


/**
 * @summary Get site settings
 */

export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateSettingsUrl = () => {




  return `/api/settings`
}

/**
 * @summary Update site settings (admin only)
 */
export const updateSettings = async (siteSettingsUpdate: SiteSettingsUpdate, options?: RequestInit): Promise<SiteSettings> => {

  return customFetch<SiteSettings>(getUpdateSettingsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      siteSettingsUpdate,)
  }
);}




export const getUpdateSettingsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,{data: BodyType<SiteSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,{data: BodyType<SiteSettingsUpdate>}, TContext> => {

const mutationKey = ['updateSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettings>>, {data: BodyType<SiteSettingsUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettings>>>
    export type UpdateSettingsMutationBody = BodyType<SiteSettingsUpdate>
    export type UpdateSettingsMutationError = ErrorType<unknown>

    /**
 * @summary Update site settings (admin only)
 */
export const useUpdateSettings = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,{data: BodyType<SiteSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateSettings>>,
        TError,
        {data: BodyType<SiteSettingsUpdate>},
        TContext
      > => {
      return useMutation(getUpdateSettingsMutationOptions(options));
    }

