/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Login with username and password
 */
export const LoginBody = zod.object({
  "username": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
}),
  "token": zod.string()
})


/**
 * @summary Logout current user
 */
export const LogoutResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string().optional()
})


/**
 * @summary Get current logged-in user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary List all users (admin only)
 */
export const ListUsersResponseItem = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary Create a new user (admin only)
 */
export const CreateUserBody = zod.object({
  "username": zod.string(),
  "password": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number().optional(),
  "expiresAt": zod.string().nullish()
})


/**
 * @summary Get user by ID
 */
export const GetUserParams = zod.object({
  "id": zod.coerce.number()
})

export const GetUserResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Update user (admin only)
 */
export const UpdateUserParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateUserBody = zod.object({
  "username": zod.string().optional(),
  "password": zod.string().optional(),
  "role": zod.enum(['admin', 'member']).optional(),
  "balance": zod.number().optional(),
  "isBlocked": zod.boolean().optional(),
  "expiresAt": zod.string().nullish()
})

export const UpdateUserResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Delete user (admin only)
 */
export const DeleteUserParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteUserResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string().optional()
})


/**
 * @summary Add or set balance for user (admin only)
 */
export const AdjustBalanceParams = zod.object({
  "id": zod.coerce.number()
})

export const AdjustBalanceBody = zod.object({
  "amount": zod.number(),
  "mode": zod.enum(['add', 'set'])
})

export const AdjustBalanceResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Transfer balance to another user by username
 */
export const TransferBalanceBody = zod.object({
  "toUsername": zod.string(),
  "amount": zod.number()
})

export const TransferBalanceResponse = zod.object({
  "success": zod.boolean(),
  "fromBalance": zod.number(),
  "toUsername": zod.string(),
  "amount": zod.number()
})


/**
 * @summary Renew account expiry using balance (member only)
 */
export const RenewAccountBody = zod.object({
  "days": zod.number()
})

export const RenewAccountResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'member']),
  "balance": zod.number(),
  "isBlocked": zod.boolean(),
  "failedAttempts": zod.number(),
  "expiresAt": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary List all gacha chests
 */
export const ListChestsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.enum(['basic', 'rare', 'mythic']),
  "imageUrl": zod.string().nullish(),
  "costPerPull": zod.number(),
  "isActive": zod.boolean(),
  "itemCount": zod.number()
})
export const ListChestsResponse = zod.array(ListChestsResponseItem)


/**
 * @summary Create a chest (admin only)
 */
export const CreateChestBody = zod.object({
  "name": zod.string(),
  "type": zod.enum(['basic', 'rare', 'mythic']),
  "imageUrl": zod.string().optional(),
  "costPerPull": zod.number(),
  "isActive": zod.boolean().optional()
})


/**
 * @summary Update chest (admin only)
 */
export const UpdateChestParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateChestBody = zod.object({
  "name": zod.string().optional(),
  "type": zod.enum(['basic', 'rare', 'mythic']).optional(),
  "imageUrl": zod.string().optional(),
  "costPerPull": zod.number().optional(),
  "isActive": zod.boolean().optional()
})

export const UpdateChestResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.enum(['basic', 'rare', 'mythic']),
  "imageUrl": zod.string().nullish(),
  "costPerPull": zod.number(),
  "isActive": zod.boolean(),
  "itemCount": zod.number()
})


/**
 * @summary Delete chest (admin only)
 */
export const DeleteChestParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteChestResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string().optional()
})


/**
 * @summary List all gacha items (optionally filter by chest_id)
 */
export const ListItemsQueryParams = zod.object({
  "chest_id": zod.coerce.number().optional()
})

export const ListItemsResponseItem = zod.object({
  "id": zod.number(),
  "chestId": zod.number(),
  "name": zod.string(),
  "imageUrl": zod.string().nullish(),
  "chance": zod.number(),
  "rarity": zod.enum(['common', 'rare', 'legendary'])
})
export const ListItemsResponse = zod.array(ListItemsResponseItem)


/**
 * @summary Create a gacha item (admin only)
 */
export const CreateItemBody = zod.object({
  "chestId": zod.number(),
  "name": zod.string(),
  "imageUrl": zod.string().optional(),
  "chance": zod.number(),
  "rarity": zod.enum(['common', 'rare', 'legendary'])
})


/**
 * @summary Update gacha item (admin only)
 */
export const UpdateItemParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateItemBody = zod.object({
  "name": zod.string().optional(),
  "imageUrl": zod.string().optional(),
  "chance": zod.number().optional(),
  "rarity": zod.enum(['common', 'rare', 'legendary']).optional()
})

export const UpdateItemResponse = zod.object({
  "id": zod.number(),
  "chestId": zod.number(),
  "name": zod.string(),
  "imageUrl": zod.string().nullish(),
  "chance": zod.number(),
  "rarity": zod.enum(['common', 'rare', 'legendary'])
})


/**
 * @summary Delete gacha item (admin only)
 */
export const DeleteItemParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteItemResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string().optional()
})


/**
 * @summary Pull gacha from a chest
 */
export const PullGachaBody = zod.object({
  "chestId": zod.number()
})

export const PullGachaResponse = zod.object({
  "item": zod.object({
  "id": zod.number(),
  "chestId": zod.number(),
  "name": zod.string(),
  "imageUrl": zod.string().nullish(),
  "chance": zod.number(),
  "rarity": zod.enum(['common', 'rare', 'legendary'])
}),
  "chest": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "type": zod.enum(['basic', 'rare', 'mythic']),
  "imageUrl": zod.string().nullish(),
  "costPerPull": zod.number(),
  "isActive": zod.boolean(),
  "itemCount": zod.number()
}),
  "remainingBalance": zod.number()
})


/**
 * @summary Get gacha pull history for current user
 */
export const ListGachaHistoryResponseItem = zod.object({
  "id": zod.number(),
  "itemName": zod.string(),
  "itemImageUrl": zod.string().nullish(),
  "itemRarity": zod.string(),
  "chestName": zod.string(),
  "chestType": zod.string(),
  "pulledAt": zod.string()
})
export const ListGachaHistoryResponse = zod.array(ListGachaHistoryResponseItem)


/**
 * @summary Get gacha statistics (admin dashboard)
 */
export const GetGachaStatsResponse = zod.object({
  "totalPulls": zod.number(),
  "totalUsers": zod.number(),
  "activeUsers": zod.number(),
  "totalBalanceCirculating": zod.number(),
  "topItems": zod.array(zod.object({
  "itemName": zod.string(),
  "pullCount": zod.number()
}))
})


/**
 * @summary Get site settings
 */
export const GetSettingsResponse = zod.object({
  "siteName": zod.string(),
  "renewalCostPerDay": zod.number(),
  "maintenanceMode": zod.boolean(),
  "primaryColor": zod.string(),
  "bgType": zod.enum(['particles', 'gradient', 'image', 'color']),
  "bgValue": zod.string(),
  "themeMode": zod.enum(['dark', 'light']),
  "customLabels": zod.string(),
  "musicUrl": zod.string()
})


/**
 * @summary Update site settings (admin only)
 */
export const UpdateSettingsBody = zod.object({
  "siteName": zod.string().optional(),
  "renewalCostPerDay": zod.number().optional(),
  "maintenanceMode": zod.boolean().optional(),
  "primaryColor": zod.string().optional(),
  "bgType": zod.enum(['particles', 'gradient', 'image', 'color']).optional(),
  "bgValue": zod.string().optional(),
  "themeMode": zod.enum(['dark', 'light']).optional(),
  "customLabels": zod.string().optional(),
  "musicUrl": zod.string().optional()
})

export const UpdateSettingsResponse = zod.object({
  "siteName": zod.string(),
  "renewalCostPerDay": zod.number(),
  "maintenanceMode": zod.boolean(),
  "primaryColor": zod.string(),
  "bgType": zod.enum(['particles', 'gradient', 'image', 'color']),
  "bgValue": zod.string(),
  "themeMode": zod.enum(['dark', 'light']),
  "customLabels": zod.string(),
  "musicUrl": zod.string()
})


