/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type BalanceAdjustMode = typeof BalanceAdjustMode[keyof typeof BalanceAdjustMode];
export declare const BalanceAdjustMode: {
    readonly add: "add";
    readonly set: "set";
};
//# sourceMappingURL=balanceAdjustMode.d.ts.map