/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */

export type BalanceAdjustMode = typeof BalanceAdjustMode[keyof typeof BalanceAdjustMode];


export const BalanceAdjustMode = {
  add: 'add',
  set: 'set',
} as const;
