/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { BalanceAdjustMode } from './balanceAdjustMode';

export interface BalanceAdjust {
  amount: number;
  mode: BalanceAdjustMode;
}
