/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type ChestInputType = typeof ChestInputType[keyof typeof ChestInputType];
export declare const ChestInputType: {
    readonly basic: "basic";
    readonly rare: "rare";
    readonly mythic: "mythic";
};
//# sourceMappingURL=chestInputType.d.ts.map