/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */

export type ChestType = typeof ChestType[keyof typeof ChestType];


export const ChestType = {
  basic: 'basic',
  rare: 'rare',
  mythic: 'mythic',
} as const;
