/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { ChestUpdateType } from './chestUpdateType';

export interface ChestUpdate {
  name?: string;
  type?: ChestUpdateType;
  imageUrl?: string;
  costPerPull?: number;
  isActive?: boolean;
}
