/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */

export type ChestInputType = typeof ChestInputType[keyof typeof ChestInputType];


export const ChestInputType = {
  basic: 'basic',
  rare: 'rare',
  mythic: 'mythic',
} as const;
