/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { ChestType } from './chestType';

export interface Chest {
  id: number;
  name: string;
  type: ChestType;
  /** @nullable */
  imageUrl?: string | null;
  costPerPull: number;
  isActive: boolean;
  itemCount: number;
}
