/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type ChestUpdateType = typeof ChestUpdateType[keyof typeof ChestUpdateType];
export declare const ChestUpdateType: {
    readonly basic: "basic";
    readonly rare: "rare";
    readonly mythic: "mythic";
};
//# sourceMappingURL=chestUpdateType.d.ts.map