/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { ChestInputType } from './chestInputType';

export interface ChestInput {
  name: string;
  type: ChestInputType;
  imageUrl?: string;
  costPerPull: number;
  isActive?: boolean;
}
