/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { GachaStatsTopItemsItem } from './gachaStatsTopItemsItem';
export interface GachaStats {
    totalPulls: number;
    totalUsers: number;
    activeUsers: number;
    totalBalanceCirculating: number;
    topItems: GachaStatsTopItemsItem[];
}
//# sourceMappingURL=gachaStats.d.ts.map