/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type GachaItemInputRarity = typeof GachaItemInputRarity[keyof typeof GachaItemInputRarity];
export declare const GachaItemInputRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
//# sourceMappingURL=gachaItemInputRarity.d.ts.map