/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type GachaItemUpdateRarity = typeof GachaItemUpdateRarity[keyof typeof GachaItemUpdateRarity];
export declare const GachaItemUpdateRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
//# sourceMappingURL=gachaItemUpdateRarity.d.ts.map