/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { GachaItemRarity } from './gachaItemRarity';

export interface GachaItem {
  id: number;
  chestId: number;
  name: string;
  /** @nullable */
  imageUrl?: string | null;
  chance: number;
  rarity: GachaItemRarity;
}
