/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type GachaItemRarity = typeof GachaItemRarity[keyof typeof GachaItemRarity];
export declare const GachaItemRarity: {
    readonly common: "common";
    readonly rare: "rare";
    readonly legendary: "legendary";
};
//# sourceMappingURL=gachaItemRarity.d.ts.map