/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export interface GachaHistory {
    id: number;
    itemName: string;
    /** @nullable */
    itemImageUrl?: string | null;
    itemRarity: string;
    chestName: string;
    chestType: string;
    pulledAt: string;
}
//# sourceMappingURL=gachaHistory.d.ts.map