/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { GachaItemInputRarity } from './gachaItemInputRarity';

export interface GachaItemInput {
  chestId: number;
  name: string;
  imageUrl?: string;
  chance: number;
  rarity: GachaItemInputRarity;
}
