/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type ListItemsParams = {
    chest_id?: number;
};
//# sourceMappingURL=listItemsParams.d.ts.map