/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */

export type SiteSettingsUpdateThemeMode = typeof SiteSettingsUpdateThemeMode[keyof typeof SiteSettingsUpdateThemeMode];


export const SiteSettingsUpdateThemeMode = {
  dark: 'dark',
  light: 'light',
} as const;
