/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type SiteSettingsBgType = typeof SiteSettingsBgType[keyof typeof SiteSettingsBgType];
export declare const SiteSettingsBgType: {
    readonly particles: "particles";
    readonly gradient: "gradient";
    readonly image: "image";
    readonly color: "color";
};
//# sourceMappingURL=siteSettingsBgType.d.ts.map