/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type SiteSettingsUpdateBgType = typeof SiteSettingsUpdateBgType[keyof typeof SiteSettingsUpdateBgType];
export declare const SiteSettingsUpdateBgType: {
    readonly particles: "particles";
    readonly gradient: "gradient";
    readonly image: "image";
    readonly color: "color";
};
//# sourceMappingURL=siteSettingsUpdateBgType.d.ts.map