/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type SiteSettingsThemeMode = typeof SiteSettingsThemeMode[keyof typeof SiteSettingsThemeMode];
export declare const SiteSettingsThemeMode: {
    readonly dark: "dark";
    readonly light: "light";
};
//# sourceMappingURL=siteSettingsThemeMode.d.ts.map