/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */

export type SiteSettingsUpdateBgType = typeof SiteSettingsUpdateBgType[keyof typeof SiteSettingsUpdateBgType];


export const SiteSettingsUpdateBgType = {
  particles: 'particles',
  gradient: 'gradient',
  image: 'image',
  color: 'color',
} as const;
