/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { SiteSettingsBgType } from './siteSettingsBgType';
import type { SiteSettingsThemeMode } from './siteSettingsThemeMode';

export interface SiteSettings {
  siteName: string;
  renewalCostPerDay: number;
  maintenanceMode: boolean;
  primaryColor: string;
  bgType: SiteSettingsBgType;
  bgValue: string;
  themeMode: SiteSettingsThemeMode;
  customLabels: string;
  musicUrl: string;
}
