/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { SiteSettingsUpdateBgType } from './siteSettingsUpdateBgType';
import type { SiteSettingsUpdateThemeMode } from './siteSettingsUpdateThemeMode';

export interface SiteSettingsUpdate {
  siteName?: string;
  renewalCostPerDay?: number;
  maintenanceMode?: boolean;
  primaryColor?: string;
  bgType?: SiteSettingsUpdateBgType;
  bgValue?: string;
  themeMode?: SiteSettingsUpdateThemeMode;
  customLabels?: string;
  musicUrl?: string;
}
