/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export interface TransferResult {
    success: boolean;
    fromBalance: number;
    toUsername: string;
    amount: number;
}
//# sourceMappingURL=transferResult.d.ts.map