/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type UserInputRole = typeof UserInputRole[keyof typeof UserInputRole];
export declare const UserInputRole: {
    readonly admin: "admin";
    readonly member: "member";
};
//# sourceMappingURL=userInputRole.d.ts.map