/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
export type UserUpdateRole = typeof UserUpdateRole[keyof typeof UserUpdateRole];
export declare const UserUpdateRole: {
    readonly admin: "admin";
    readonly member: "member";
};
//# sourceMappingURL=userUpdateRole.d.ts.map