/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from './userRole';
export interface User {
    id: number;
    username: string;
    role: UserRole;
    balance: number;
    isBlocked: boolean;
    failedAttempts: number;
    /** @nullable */
    expiresAt?: string | null;
    createdAt: string;
}
//# sourceMappingURL=user.d.ts.map