/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AndraDev Growtopia Gacha API
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateRole } from './userUpdateRole';
export interface UserUpdate {
    username?: string;
    password?: string;
    role?: UserUpdateRole;
    balance?: number;
    isBlocked?: boolean;
    /** @nullable */
    expiresAt?: string | null;
}
//# sourceMappingURL=userUpdate.d.ts.map